default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: castaway_development
  username: postgres
  password: postgres
  host: db

test:
  <<: *default
  username: postgres
  password: postgres
  host: db
  database: castaway_test

production:
  <<: *default
  database: castaway_production
  username: castaway
  password: <%= ENV['CASTAWAY_DATABASE_PASSWORD'] %>
